version: '3.8'
networks:
  my_master_slave_mysql:
    driver: bridge

services:
  db_master_svc:
    image: mysql:8.0
    container_name: db_master_svc
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: db_replication_dev
      MYSQL_USER: piuw_dev
      MYSQL_PASSWORD: zxcv123
    ports:
      - '3306:3306'
    volumes:
      - db_master_volume:/var/lib/mysql
    networks:
      my_master_slave_mysql:
        aliases:
          - db_network_master

  db_replica_svc:
    image: mysql:8.0
    container_name: db_replica_svc
    restart: always
    depends_on:
      - db_master_svc
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: db_replication_dev
      MYSQL_REPLICATION_SOURCE: db_master_svc:3306
    ports:
      - '3307:3306'
    volumes:
      - db_replica_volume:/var/lib/mysql
    networks:
      my_master_slave_mysql:
        aliases:
          - db_network_replica

volumes:
  db_master_volume:
  db_replica_volume:
