version: '3.8'
networks:
  my_master_slave_mysql:
    driver: bridge

services:
  db_primary:
    image: mysql:8.0
    container_name: mysql_primary
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: db_replication_dev
      MYSQL_USER: piuw_dev
      MYSQL_PASSWORD: zxcv123
    ports:
      - '3306:3306'
    volumes:
      - mysql_primary:/var/lib/mysql
    command:
      - mysqld
      - --server-id=1
      - --log-bin=mysql-bin
      - --binlog-do-db=db_replication_dev
    networks:
      my_master_slave_mysql:
        aliases:
          - db_primary

  db_secondary:
    image: mysql:8.0
    container_name: mysql_secondary
    restart: always
    depends_on:
      - db_primary
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: db_replication_dev
      MYSQL_USER: piuw_dev
      MYSQL_PASSWORD: zxcv123
      MYSQL_REPLICATION_SOURCE: db_primary:3306
    ports:
      - '3307:3306'
    volumes:
      - mysql_secondary_data:/var/lib/mysql
    command:
      - mysqld
      - --server-id=2
      - --log-bin=mysql-bin
      - --binlog-do-db=db_replication_dev
    networks:
      my_master_slave_mysql:
        aliases:
          - db_primary

volumes:
  mysql_primary:
  mysql_secondary_data:
